EmptyDemo/Controllers/CartController.cs
using EmptyDemo.Models;
using EmptyDemo.Services.IRepositories;
using EmptyDemo.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EmptyDemo.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private readonly ShoppingCart _shoppingCart;
        private readonly IItemsRepo _items;

        public CartController(IItemsRepo itemsRepo, ShoppingCart shoppingCart)
        {
            _items = itemsRepo;
            _shoppingCart = shoppingCart;
        }

        
        public IActionResult Index(int ItemId)
        {
            var items = _shoppingCart.GetShoppingItems().ToList();
            _shoppingCart.ShoppingCartItems = items;

            var shoppingCartViewModel = new ShoppingCartViewModel()
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetTotal()

            };

            return View(shoppingCartViewModel);
        }

        public IActionResult AddToCart(int ItemId)
        {
            var item = _items.GetItemWithId(ItemId);

            if(item != null)
            {
                _shoppingCart.AddToCart(item);
            }

            return RedirectToAction("Index");
            //return RedirectToAction("Index", "Home"); //Action, Controller
        }

        [Authorize]
        public IActionResult RemoveFromCart(int ItemId)
        {
            var item = _items.GetItemWithId(ItemId);

            if (item != null)
            {
                _shoppingCart.RemoveFromcart(item);
            }

            return RedirectToAction("Index");
        }

        [Authorize]
        public IActionResult ClearCart()
        {
            _shoppingCart.ClearCart();
            return RedirectToAction("Index");
        }
    }
}

EmptyDemo/Controllers/DetailsController.cs
using EmptyDemo.Services.IRepositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EmptyDemo.Controllers
{
    [Authorize]
    public class DetailsController : Controller
    {
        private readonly IItemsRepo _itemsRepo;
        public DetailsController(IItemsRepo itemsRepo)
        {
            _itemsRepo = itemsRepo;
        }
        public IActionResult Index(int ItemId)
        {
            var item = _itemsRepo.GetItemWithId(ItemId);
            return View(item);
        }
    }
}

EmptyDemo/Views/Shared/_ItemPartial.cshtml
@model Item 

<div class="col-sm-4">
    <div class="card-deck">
        <div class="card shadow">
            <img class="card-img-top img-thumbnail" src="@Model.ImageURL" style="width:100%; height:300px" />
            <div class="card-body text-center">
                <div class="row">
                    <div class="col-md-8">
                        <h6 class="card-title">
                            <a asp-controller="Details" asp-action="Index" asp-route-ItemId="@Model.ItemId"
                               style="text-decoration:none;">
                                @Model.ItemName
                            </a>
                        </h6>
                    </div>
                    <div class="col-md-4">
                        <h6>&#8377 @Model.Price</h6>
                    </div>
                </div>

                <p class="card-text">
                    &ldquo; @Model.ItemDescription &rdquo;
                </p>
                <a asp-area="" asp-controller="Details" asp-action="Index" asp-route-ItemId="@Model.ItemId" target="_blank" class="btn btn-primary btn-sm">View</a>
                <a asp-controller="Cart" asp-action="AddToCart" asp-route-ItemId="@Model.ItemId" target="_blank" class="btn btn-success btn-sm">Add to Cart</a>
            </div>
        </div>
    </div>
</div>

EmptyDemo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Responsive sidebar template with sliding effect and dropdown menu based on bootstrap 3">
    <title>Foodie Point</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
          crossorigin="anonymous">
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <link href="~/css/style.css" rel="stylesheet" />

    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

</head>

<body>
    <div class="page-wrapper chiller-theme toggled">
        <a id="show-sidebar" class="btn btn-sm btn-dark" href="#">
            <i class="fas fa-bars"></i>
        </a>
        <nav id="sidebar" class="sidebar-wrapper">
            <div class="sidebar-content">
                <div class="sidebar-brand">
                    <a href="#">Foodie Point</a>
                    <div id="close-sidebar">
                        <i class="fas fa-times"></i>
                    </div>
                </div>
                <div class="sidebar-header">
                    <div class="user-pic">
                        <img class="img-responsive img-rounded" src="https://raw.githubusercontent.com/azouaoui-med/pro-sidebar-template/gh-pages/src/img/user.jpg"
                             alt="User picture">
                    </div>
                    <div class="user-info">
                        <span class="user-name">
                            <strong>
                                Shivshakti Singh
                            </strong>
                        </span>
                        <span class="user-role">Owner</span>
                        <span class="user-status">
                            <i class="fa fa-circle"></i>
                            <span>Available</span>
                        </span>
                    </div>
                </div>
                <!-- sidebar-header  -->
                @*<div class="sidebar-search">
                    <div>
                        <div class="input-group">
                            <form method="post">
                                <input id="srch" type="text" class="form-control search-menu" placeholder="Search an Item...">
                                <div class="input-group-append">
                                    <span class="input-group-text">
                                        <i class="fa fa-search" aria-hidden="true"></i>
                                    </span>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>*@
                @*@await Component.InvokeAsync("Searchbar")*@
                <!-- sidebar-search  -->
                <div class="sidebar-menu">
                    <ul>
                        <li class="header-menu">
                            <span>General</span>
                        </li>
                        <li>
                            <a asp-controller="Home" asp-action="Dashboard">
                                <i class="fa fa-tachometer-alt"></i>
                                <span>Dashboard</span>
                                <span class="badge badge-pill badge-warning">Hot New</span>
                            </a>

                        </li>

                        <li class="sidebar-dropdown">
                            <a href="#">
                                <i class="far fa-gem"></i>
                                <span>Menu</span>
                            </a>
                            <div class="sidebar-submenu">
                                <ul>
                                    @await Component.InvokeAsync("CategoryMenu")
                                </ul>
                            </div>
                        </li>
                        <li>
                            <a asp-controller="Cart" asp-action="Index">
                                <i class="fa fa-shopping-cart"></i> @await Component.InvokeAsync("ContentCount")
                                <span>E-commerce</span>
                            </a>
                        </li>
                    </ul>
                </div>
                <!-- sidebar-menu  -->
            </div>
            <!-- sidebar-content  -->
            <div class="sidebar-footer">
                <a href="#">
                    <i class="fa fa-bell"></i>
                    <span class="badge badge-pill badge-warning notification">3</span>
                </a>
                <a href="#">
                    <i class="fa fa-envelope"></i>
                    <span class="badge badge-pill badge-success notification">7</span>
                </a>
                <a href="#">
                    <i class="fa fa-cog"></i>
                    <span class="badge-sonar"></span>
                </a>
                <a asp-controller="Home" asp-action="Logout">
                    <i class="fa fa-power-off"></i>
                </a>
            </div>
        </nav>
        <!-- sidebar-wrapper  -->
        <main class="page-content">
            <div class="container-fluid">
                @RenderBody()

                <footer class="text-center">
                    <div class="mb-2">
                        <small>
                            © 2021 made with <i class="fa fa-heart" style="color:red"></i> by - Shivshakti Singh
                        </small>
                    </div>
                    <div>
                        <a href="https://github.com/" target="_blank">
                            <img alt="GitHub followers" src="https://img.shields.io/github/followers/azouaoui-med?label=github&style=social" />
                        </a>
                        <a href="https://twitter.com/" target="_blank">
                            <img alt="Twitter Follow" src="https://img.shields.io/twitter/follow/azouaoui_med?label=twitter&style=social" />
                        </a>
                    </div>
                </footer>
            </div>
        </main>
        <!-- page-content" -->
    </div>
    <!-- page-wrapper -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>
    <script type="text/javascript">
        $(".sidebar-dropdown > a").click(function () {
            $(".sidebar-submenu").slideUp(200);
            if (
                $(this)
                    .parent()
                    .hasClass("active")
            ) {
                $(".sidebar-dropdown").removeClass("active");
                $(this)
                    .parent()
                    .removeClass("active");
            } else {
                $(".sidebar-dropdown").removeClass("active");
                $(this)
                    .next(".sidebar-submenu")
                    .slideDown(200);
                $(this)
                    .parent()
                    .addClass("active");
            }
        });

        $("#close-sidebar").click(function () {
            $(".page-wrapper").removeClass("toggled");
        });
        $("#show-sidebar").click(function () {
            $(".page-wrapper").addClass("toggled");
        });

    </script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

EmptyDemo/Views/Shared/_RazorLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Responsive sidebar template with sliding effect and dropdown menu based on bootstrap 3">
    <title>Foodie Point</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
          crossorigin="anonymous">
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">

   @* <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <link href="~/css/style.css" rel="stylesheet" />
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>*@
</head>
<body>
    <div id="fb-root"></div>
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v11.0&appId=2215618525242285&autoLogAppEvents=1" nonce="CfxS5nUl"></script>
    <div>
        @RenderBody()
    </div>


    <script src="~/lib/jquery/jquery.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>